[env:tally_hub]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -DCORE_DEBUG_LEVEL=0
lib_deps = 
    Wire
    WiFi
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit BusIO@^1.14.1
    h2zero/NimBLE-Arduino@^2.1.1
lib_extra_dirs = 
    lib

